# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsnXES3959gs2VOU2K2062Yo2qq4HOKO

Upload the best_model.pkl
"""

from google.colab import files
uploaded = files.upload()

!pip install streamlit

import streamlit as st
import pickle
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load the trained model (assuming you have saved the best model with pickle)
model = pickle.load(open('best_model.pkl', 'rb'))  # Make sure to save this model first!

# Set up the app interface
st.title('Iris Classifier')

# Input fields for the user to input flower features
sepal_length = st.number_input('Sepal Length', min_value=0.0, max_value=10.0, value=5.0)
sepal_width = st.number_input('Sepal Width', min_value=0.0, max_value=10.0, value=3.0)
petal_length = st.number_input('Petal Length', min_value=0.0, max_value=10.0, value=4.0)
petal_width = st.number_input('Petal Width', min_value=0.0, max_value=10.0, value=1.0)

# Prepare the input data for prediction
input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
input_data = StandardScaler().fit_transform(input_data)  # Scale features if needed

# Make a prediction when the user clicks the button
if st.button('Predict'):
    prediction = model.predict(input_data)
    st.write(f"Predicted Class: {prediction[0]}")

